### ISSUE TITLE
Profile:  Create Pop-up with opt-in where users can con confirm their willingness help grow the oC community

### ISSUE THREAD

**Issue by MaxTattenbach** [opencurrents/opencurrents#599] opened 2017-10-27 04:46 UTC
Proposed Text: 

Welcome to the openCurrents community.  We are just getting started and your contribution to growing our community is essential. If you would like to help our community grow by referring your favorite nonprofits, businesses, friends or even influencers please opt-in.  You could also receive brand ambassador status. One of our members will be in touch with you shortly.  Let's change this World one Current at a time!

**Comment by nickolashe** [comment] 2017-10-30 07:49
i think i've seen another issue related to this

**Comment by dannypernik** [comment] 2017-10-30 17:16
Duplicate of #519. Copying Max's proposed text there

**Closed** 2017-10-30 17:38 UTC
Labels: mvp, priority low, priority medium
