### ISSUE TITLE
Nominate an admin: wrong message in the popup

### ISSUE THREAD

**Issue by karbmk** [opencurrents/opencurrents#368] opened 2017-08-25 16:33 UTC
![screen shot 2017-08-25 at 11 27 49 am](https://user-images.githubusercontent.com/8406712/29723144-1d20c5e2-8989-11e7-9ed4-401074f22e70.png)

**Comment by MaxTattenbach** [comment] 2017-08-25 16:41
@nickolashe  @dannypernik 

Danny, when going over the manual tracking with Karthik I noticed this issue on the pop-up.  

Note this shows up with when Admin is not found and the messaging seems more for a pop-up for when a org isn't found.   Message should be changed.  I suggest this message:

Thanks for contributing for the greater good!  Every hour needs to be approved by a supervisor/admin of the organization you volunteer for.  If your supervisor or volunteer coordinator is not listed please invite him to join openCurrents so he/she can approve your hours and you can earn Currents.

**Comment by MaxTattenbach** [comment] 2017-08-25 16:42
@dannypernik @nickolashe On this note I think that there should also be a pop-up.  (No need to delay product for this) for when I want to track my time and my organization is not listed.  I think that is perhaps the best place for a volunteer to nominate and organization.

**Comment by nickolashe** [comment] 2017-08-25 17:22
@karbmk @MaxTattenbach I think this is a duplicate of https://github.com/opencurrents/opencurrents/issues/367

**Comment by nickolashe** [comment] 2017-08-25 17:23
please do a quick search of existing issues before opening a new one

**Closed** 2017-08-25 17:23 UTC
Labels: priority medium

**Comment by MaxTattenbach** [comment] 2017-08-25 19:16
@nickolashe  Sounds good!  I'll check more carefully prior adding a new issue.
