### ISSUE TITLE
Invite volunteers.  It should have a copy and paste link for someone to send to its networks

### ISSUE THREAD

**Issue by MaxTattenbach** [opencurrents/opencurrents#302] opened 2017-08-16 00:04 UTC
![send invitation](https://user-images.githubusercontent.com/26234440/29341827-829f97da-81ec-11e7-9a18-6676812bf6bc.PNG)

**Comment by dannypernik** [comment] 2017-10-27 19:17
duplicate of #219

**Closed by dannypernik** 2017-10-27 19:17 UTC
