### ISSUE TITLE
profile: List user's Redeemed offers

### ISSUE THREAD

**Issue by dannypernik** [opencurrents/opencurrents#534] opened 2017-10-16 00:21 UTC
I've included `<!-- % if % -->` comments wherever tags are required, including for the "Status" title (we don't want to show Status title if no offers are present)

**Comment by nickolashe** [comment] 2017-10-16 08:06
duplicate of #501

**Comment by nickolashe** [comment] 2017-10-16 08:07
@dannypernik can you please take a second to check the list of existing issues in the milestone before opening a new one

**Closed by nickolashe** 2017-10-16 08:07 UTC
Labels: priority medium
