### ISSUE TITLE
Time-Tracker:  Volunteers should be able to see the past hours subimtted for the week. 

### ISSUE THREAD

**Issue by MaxTattenbach** [opencurrents/opencurrents#317] opened 2017-08-16 14:18 UTC
I think it should display below  the form. 
![hours submitteed stamp](https://user-images.githubusercontent.com/26234440/29367818-b5de86ac-8263-11e7-8bd8-fa4f36f8df71.PNG)

**Comment by nickolashe** [comment] 2017-08-16 22:31
duplicate of #307

**Closed** 2017-08-17 20:38 UTC
Labels: priority medium
