### ISSUE TITLE
Nominate Org:  Incorrect email form is sent to New Admin.   It should be Volunteer-invites-Org  not Volunteer-invites-admin

### ISSUE THREAD

**Issue by MaxTattenbach** [opencurrents/opencurrents#926] opened 2017-12-29 00:57 UTC

**Comment by nickolashe** [comment] 2018-01-03 02:13
@dannypernik @MaxTattenbach which template is this?

**Comment by MaxTattenbach** [comment] 2018-01-03 21:20
@nickolashe this is the form.   I am going to add new label "Needs discussion".  Currently, this form is only being sent to biz dev and not to new admin so it's not an issue.   I think the form's proper functionality is to send email to both biz dev and admin.  In which case if email is associated to org or biz it should not send the email. 

We can discuss after our 1/12 Release

![image](https://user-images.githubusercontent.com/26234440/34539980-6fba1ada-f098-11e7-8abf-e3e6f81edeb6.png)

**Comment by nickolashe** [comment] 2018-01-04 20:18
@tevtonez this one should be as simple as adding a validation method on `contact_email` field to `OrgNomination` form:
https://github.com/opencurrents/opencurrents/blob/develop/openCurrents/templates/hours-detail.html#L87

but lets hold off one this before we clarify something with @MaxTattenbach:

**Comment by nickolashe** [comment] 2018-01-04 20:20
@MaxTattenbach @dannypernik : 

1. what if the org already exists, but given admin is not affiliated?
2. what if the admin exists in the system but the org does not, i.e. admin is affiliated with a different org?

**Comment by MaxTattenbach** [comment] 2018-01-05 01:03
@dannypernik @nickolashe per discussed.
 
1. display status message if new admin is associated with ANY org (npf or business).  No matter if its the one nominated on the form or not.   Status/error mesage should say:  Thanks for nominating [Business/Org], it seems that  [email] is already affiliated with an organization on openCurrents.  

If org (npf or business) already exists in DB.  Then status message when submitting form should be.  Thanks for nominating [Business/Org], it seems that [Business/Org] is already active openCurrents. 

For both unhappy paths, emails let's still send emails to biz dev.  It's valuable for us to know what folks are nominating.

**Comment by nickolashe** [comment] 2018-01-05 11:30
@tevtonez this has been agreed on, let’s proceed with this one based on the above description

**Comment by MaxTattenbach** [comment] 2018-01-07 02:44
@tevtonez not sure if the Happy path was not written out and this is causing the issue but if org is not existent and/or admin is existent but not affiliated with an org then the green status message should show up saying. 
Thanks for nominating (org) and helping us grow our community. 

Currently, I can't get to the happy path with this form. 

Note that in all cases we should be receiving the email in either happy or unhappy path.

**Comment by tevtonez** [comment] 2018-01-08 10:01
@MaxTattenbach 
the current implementation is next:
1. if nominated org exists already:
- we show red msg `Thanks for nominating {Org}, it seems that {Org} is already active openCurrents.`, email isn't sent.
2. if Org doesn't exist and user exists but not affiliated OR  Org doesn't exist and user doesn't exists:
- we show green msg `Thank you for nominating {Org}! We will reach out soon.`, email sent.
3. if Org doesn't exist but user exists and affiliated:
- we show red msg `Thanks for nominating {Org}, it seems that {User} is already affiliated with an organization on openCurrents.`, email isn't sent

**Comment by MaxTattenbach** [comment] 2018-01-08 23:00
@tevtonez  I am not able to get 2 (happy path to work) no way to submit the form.

1. see that user costasverdes@gmail.com doesn't exist in DB
![image](https://user-images.githubusercontent.com/26234440/34696505-b4bd0a16-f494-11e7-82a7-d8380e8d5c30.png)

2. Nominate Org from /nominate
![image](https://user-images.githubusercontent.com/26234440/34696557-e4b58cc0-f494-11e7-8ac4-3ec68e5cabe8.png)

3.
![image](https://user-images.githubusercontent.com/26234440/34696605-14641b3a-f495-11e7-93dc-4521f67ffe78.png)

**Comment by tevtonez** [comment] 2018-01-08 23:04
this is really weird.
on kostya_profile_additions branch:
![screenshot 2018-01-09 00 03 24](https://user-images.githubusercontent.com/343347/34696863-a933ad76-f4d0-11e7-8014-6b1f0f808cb6.png)
![screenshot 2018-01-09 00 03 32](https://user-images.githubusercontent.com/343347/34696867-ad89fdda-f4d0-11e7-8915-0683aa76c8aa.png)

**Comment by nickolashe** [comment] 2018-01-09 00:13
not sure what the issue is, commented on this on #967

**Comment by MaxTattenbach** [comment] 2018-01-10 00:16
1. When nominating existing user costasverdes@gmail.com related to existing Org. 
Status message should be red. 

![image](https://user-images.githubusercontent.com/26234440/34749675-67ebcc20-f568-11e7-9bb9-cf1a312eca74.png)

2.  When nominating existing user affiliated with Org but using capital letters in the email address.  Note it should not be capslock sensitive

![image](https://user-images.githubusercontent.com/26234440/34749725-ab0a69ee-f568-11e7-8c61-643b0852af3b.png)
![image](https://user-images.githubusercontent.com/26234440/34749736-ba79f0fc-f568-11e7-89fd-2c292037f928.png)


3.  When nominating existing org with new admin. Status message should be red. 
![image](https://user-images.githubusercontent.com/26234440/34749795-045008ec-f569-11e7-9506-7f17e7cb0f26.png)

4.

**Comment by MaxTattenbach** [comment] 2018-01-10 00:45
@tevtonez  I here write the paths again for clarity. 

1.	Happy Path: 
if Org doesn't exist and user exists but not affiliated to any org (NPF or Biz) OR Org doesn't exist and user doesn't exists:

-Status Message: (Green) Thank you for nominating {Org} and growing our community! We will reach out soon.
- Email sent to biz dev and new admin. 

2.	Un happy path
If nominated org exists already no matter the if user is afiliated or not. :
- we show red msg.  It seems that {Org} is already active openCurrents.  Thanks for the nomination!
- Email sent to biz dev.  Email not sent to new admin. 

3.	Un happy path
If user exists and affiliated with any org (NPF or BIZ):
- we show red msg.  It seems that {User} is already affiliated with an organization on openCurrents. Thanks for the nomination!
- Email Sent to Biz Dev and not sent to Admin.

**Comment by MaxTattenbach** [comment] 2018-01-10 00:59
@tevtonez  this is the email template that should be sent to admin.   I believe its: Invite_Admin_New Org (or something similar)


![image](https://user-images.githubusercontent.com/26234440/34750855-ffab111e-f56e-11e7-9f9a-e30e95ab6b14.png)

**Comment by nickolashe** [comment] 2018-01-10 07:19
@MaxTattenbach @dannypernik continuation of work on this task is pending review of the use cases, put together here:
https://docs.google.com/spreadsheets/d/15mnrkl4Rc5dsFX8VAGOeuPPfCQTPHyOWV1SVwkXIqNQ/edit?ts=5a3acf6c#gid=1026415208

**Comment by MaxTattenbach** [comment] 2018-01-10 17:58
@nickolashe just completed this use case thanks for taking the lead with doc

**Comment by tevtonez** [comment] 2018-01-13 13:07
this is the email I receive now as new/existing non-affiliated user
![screenshot 2018-01-13 13 58 29](https://user-images.githubusercontent.com/343347/34906298-215ea59c-f86b-11e7-81a5-48c0a48587c5.png)

**Comment by nickolashe** [comment] 2018-01-13 21:40
@tevtonez has this been merged yet?

**Comment by tevtonez** [comment] 2018-01-14 12:32
@nickolashe nope, it's a part of #988 PR

**Comment by MaxTattenbach** [comment] 2018-01-15 16:23
@tevtonez  The email above is incorrect.   New Admin receiving the email should receive volunteer_invites_org.  

@dannypernik could you please make sure the name is the proper one.  I feel we have been going around this simple issue for a long time.   Please make sure you can point Kostya to the proper template.

This is the email received by new admin which is incorrect. 

![image](https://user-images.githubusercontent.com/26234440/34951814-1f6b777e-f9dd-11e7-8ba0-343643121284.png)

**Comment by dannypernik** [comment] 2018-01-15 16:43
@tevtonez you are using the correct template. I need to make an edit to that template in Mailchimp.

**Comment by nickolashe** [comment] 2018-01-15 19:38
@tevtonez this should be a rather quick fix, what do you think?

**Comment by nickolashe** [comment] 2018-01-15 23:10
@dannypernik is the required template ready to go?

**Comment by dannypernik** [comment] 2018-01-15 23:27
@nickolashe @tevtonez yes, the template is `volunteer-nominates-org`

**Comment by tevtonez** [comment] 2018-01-16 08:04
ok, so this is what I get when using `volunteer-nominates-org` template
![screenshot 2018-01-16 09 03 31](https://user-images.githubusercontent.com/343347/34977816-50185bd4-fa9c-11e7-8bf0-138f17882539.png)

**Closed** 2018-01-17 15:18 UTC
Labels: mvp yes, priority low
