### ISSUE TITLE
Time-tracker:  Volunteer is able to submit future hours on same day or future day

### ISSUE THREAD

**Issue by MaxTattenbach** [opencurrents/opencurrents#313] opened 2017-08-16 13:19 UTC
Note on the Admin side he is not able to see the hours, when manually tracked prior current time.   Unclear to what is happening on the backed.   

I think best would be to restrict this so no hours can be submitted in forward. It should display a pop-up on the Time-Tracker

**Comment by dannypernik** [comment] 2017-09-11 17:27
Duplicate of #301

**Closed by dannypernik** 2017-09-11 17:27 UTC
Labels: bug, mvp, priority medium

**Comment by nickolashe** [comment] 2017-09-11 19:23
as well as #448
