### ISSUE TITLE
Live dashboard hour tracking checks out when page is refreshed/re-opened etc. 

### ISSUE THREAD

**Issue by everydaydaniel** [opencurrents/opencurrents#66] opened 2017-06-04 15:54 UTC
The live dashboard will check you out if you refresh the page. This is a major issue seeing that the selling point is to track hours volenteer hours. This is important because users will most likely close the window and come back to it later.

**Comment by nickolashe** [comment] 2017-06-08 06:57
Closing as a duplicate of #73

**Closed by nickolashe** 2017-06-08 06:57 UTC
Labels: priority high
