### ISSUE TITLE
Manual Tracking:  combine defer hours with a drop-down of existing org admins

### ISSUE THREAD

**Issue by MaxTattenbach** [opencurrents/opencurrents#330] opened 2017-08-17 21:04 UTC

**Comment by nickolashe** [comment] 2017-08-17 21:54
volunteer submits hours on a per-admin basis

**Comment by nickolashe** [comment] 2017-08-18 04:39
still need defer for admins not on the platform

**Comment by nickolashe** [comment] 2017-08-18 04:40
@dannypernik @MaxTattenbach can we combine defer with a dropdown of existing admins?

**Comment by MaxTattenbach** [comment] 2017-08-18 14:26
@nickolashe @dannypernik  Not sure if I am reading this correct.  But the idea is that that the volunteer can select the admin on the Record hours.  Admins should not be sending hours to other admins as they do not not know who they belong too.

**Comment by dannypernik** [comment] 2017-08-18 15:04
@maxtattenbach @nickolashe this is not high priority or critical to roll out with orgs IMO.

**Comment by nickolashe** [comment] 2017-08-18 15:08
@MaxTattenbach Danny brought up a valid point that an admin may not be registered yet. I am proposing that we have a dropdown with existing admins along with an unassigned option. Notice that the way the defer works is admins are not deferring to any one in particular, they are just saying those volunteers are not theirs. So when a new admin joins they'll still see the hours of their volunteers. Open to other suggestions.

**Comment by MaxTattenbach** [comment] 2017-08-18 15:11
Guys really nobody is doing manual tracking without an Admin supervising.
Not sure in waht organization that happens?   Are we planning to do testing
without admins?



Max Tattenbach
Co-creator
www.opencurrents.com

**Comment by MaxTattenbach** [comment] 2017-08-18 15:15
@dannypernik  I defer on your above comment.  I am volunteering at an organization that does manual tracking and I lead an organization where several admins lead volunteers - this is going to be very confusing. As it is it doesn't make sense.   We need to first get the admins on board  - no NGO account will be created with out an Admin.

**Comment by dannypernik** [comment] 2017-08-18 15:15
@maxtattenbach it's going to be confusing to volunteers if their coordinator is not yet an admin of the org. @nickolashe is suggesting that the admin assigns or invites an admin to volunteers who are not theirs. But they might not always know either. Only thing I can think of is that we have an "other" field in dropdown list and volunteer adds their name and email.

**Comment by MaxTattenbach** [comment] 2017-08-18 15:17
Or "not listed" in which case it goes to the org and all to the admins

**Comment by nickolashe** [comment] 2017-08-18 15:19
@dannypernik not sure why you got that impression, i am not actually suggesting admins invite admins necessarily. But we can offer that option, sure.

**Comment by nickolashe** [comment] 2017-08-18 15:19
@dannypernik Please read my comment above carefully

**Comment by nickolashe** [comment] 2017-08-18 15:20
@MaxTattenbach how do you see the scenario where an admin is not registered yet but some of their volunteers are?

**Comment by nickolashe** [comment] 2017-08-18 15:21
should we make admin registration a prerequisuite to their volunteers being able to track hours under them?

**Comment by MaxTattenbach** [comment] 2017-08-18 15:56
I see it very unlikely.  For testing phase all admins will be on-boarded.

**Comment by MaxTattenbach** [comment] 2017-08-18 15:57
Now we may have that be the case a few times, so I suggest lets just leave a "not listed" at the end of the dropdown with the names.

**Comment by nickolashe** [comment] 2017-08-18 16:20
@MaxTattenbach ok, how will we present these hours the admin(s) in this case?

**Comment by dannypernik** [comment] 2017-08-22 23:20
@MaxTattenbach @nickolashe The dropdown for admins works. I will add it to a new branch called time-tracker_new

If volunteer selects "Not listed", we display volunteer for all admins. We keep the "Defer" button on approve-hours for now to handle this scenario.

**Comment by MaxTattenbach** [comment] 2017-08-23 05:11
I agree w/ Danny that is what I think makes the most sense leaving the defer button for those cases when admin is not selected.   

Max

Sent from a mobile device - 
Escrito desde un móbil

**Comment by dannypernik** [comment] 2017-08-28 15:57
Duplicate of #372

**Closed by dannypernik** 2017-08-28 15:57 UTC
Labels: duplicate, priority high, question
